# Generated by Django 5.1.1 on 2024-12-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonteachingstaffprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('TEACHING_STAFF', 'Teaching Staff'), ('NON_TEACHING_STAFF', 'Non-Teaching Staff')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='admission_letter',
            field=models.FileField(blank=True, null=True, upload_to='uploads/admission_letters/'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='medical_forms',
            field=models.FileField(blank=True, null=True, upload_to='uploads/medical_forms/'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('TEACHING_STAFF', 'Teaching Staff'), ('NON_TEACHING_STAFF', 'Non-Teaching Staff')], max_length=20),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('TEACHING_STAFF', 'Teaching Staff'), ('NON_TEACHING_STAFF', 'Non-Teaching Staff')], max_length=20),
        ),
    ]
