# Generated by Django 5.1.1 on 2024-12-05 17:23

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_nonteachingstaffprofile_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonteachingstaffprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('TEACHING_STAFF', 'Teaching Staff'), ('NON_TEACHING_STAFF', 'Non-Teaching Staff')], max_length=20, validators=[api.models.RoleEnum.validate_role]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('TEACHING_STAFF', 'Teaching Staff'), ('NON_TEACHING_STAFF', 'Non-Teaching Staff')], max_length=20, validators=[api.models.RoleEnum.validate_role]),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('TEACHING_STAFF', 'Teaching Staff'), ('NON_TEACHING_STAFF', 'Non-Teaching Staff')], max_length=20, validators=[api.models.RoleEnum.validate_role]),
        ),
    ]
