# Generated by Django 5.1.1 on 2024-12-01 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonTeachingStaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_of_employment', models.DateField()),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('college_degree', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='non_teaching_staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
