# Generated by Django 5.1.1 on 2024-12-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_nonteachingstaffprofile_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonteachingstaffprofile',
            name='date_of_employment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='date_of_admission',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='date_of_employment',
            field=models.DateField(blank=True, null=True),
        ),
    ]
