# Generated by Django 5.1.1 on 2024-12-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_nonteachingstaffprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('paypal', 'Paypal'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay'), ('cryptocurrency', 'Cryptocurrency'), ('check', 'Check'), ('gift_card', 'Gift Card'), ('direct_debit', 'Direct Debit')], default='CASH', max_length=50, null=True),
        ),
    ]
