# Generated by Django 5.1.1 on 2024-12-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('TEACHER_STAFF', 'Teaching Staff'), ('NON_TEACHING_STAFF', 'Non-Teaching Staff')], default='STUDENT', max_length=20),
        ),
    ]
