# Generated by Django 5.1.1 on 2024-12-05 19:24

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_studentprofile_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='student_id_card',
            field=models.FileField(blank=True, null=True, upload_to='uploads/students_id_cards/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), api.models.validate_file_extension, api.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CREDIT_CARD', 'credit_card'), ('PAYPAL', 'paypal'), ('BANK_TRANSFER', 'bank_transfer'), ('CASH', 'cash'), ('APPLE_PAY', 'apple_pay'), ('GOOGLE_PAY', 'google_pay'), ('CRYPTOCURRENCY', 'cryptocurrency'), ('CHECK', 'check'), ('GIFT_CARD', 'gift_card'), ('DIRECT_DEBIT', 'direct_debit')], default='CASH', max_length=50, null=True),
        ),
    ]
